In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.dtype.name

'int64'

In [7]:
b = np.linspace(0,np.pi,3)

In [8]:
b

array([0.        , 1.57079633, 3.14159265])

In [9]:
a = np.arange(12)**2

In [10]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [15]:
a = np.arange(12).reshape(3,4)

In [16]:
i = np.array([[0,1],
             [1,2]])

j = np.array([[2,1],
             [3,3]])

In [17]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [18]:
i

array([[0, 1],
       [1, 2]])

In [20]:
a[2]

array([ 8,  9, 10, 11])

In [21]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
a[0,:]

array([0, 1, 2, 3])

In [25]:
a >4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])